---
fixtures:
  repositories:
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt.git
      tag: v10.0.1
    archive: https://github.com/voxpupuli/puppet-archive.git
    inifile: https://github.com/puppetlabs/puppetlabs-inifile.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    zend_common: https://github.com/zendtech/puppet-zend-common.git
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
