---
.travis.yml:
  docker_sets:
    - set: ubuntu1604-64
      options:
        script: 'bundle exec rspec spec/acceptance/php56_spec.rb'
    - set: centos7-64
      options:
        script: 'bundle exec rspec spec/acceptance/php56_spec.rb'
    - set: ubuntu1804-64
      options:
        script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    - set: ubuntu1604-64
      options:
        script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    - set: centos7-64
      options:
        script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    - set: debian9-64
      options:
        script: 'bundle exec rspec spec/acceptance/php_spec.rb'
    - set: debian8-64
      options:
        script: 'bundle exec rspec spec/acceptance/php_spec.rb'
  secure: "GOhttACuJt+3s38m4WnW5RuTgwqaAoeEQnNT+X1Ukn7KdcIk4KV8NzYU/CC0VIm8lUOnBWYJKEC4ixX/J/4Wbxox2RAoKMQrO++L0DB1zTCJnq9SfoUBMaQhXvLu+PbxAR0p3P47ozra0C+pOWDpOaxT9ecufrPQt9W9Z4aY/bs="
