name 'mayflower-php'
version '1.0.2'
author 'Mayflower'
license 'MIT'
summary 'Puppet module to manage PHP'
description 'Puppet module that aims to manage PHP on every linux distribution with sane defaults and easy, hiera-friendly configuration'
project_page 'https://github.com/Mayflower/puppet-php'

dependency 'puppetlabs/stdlib', '> 4.1.0'
dependency 'puppetlabs/apt', '> 0.0.0'
dependency 'darin/zypprepo', '> 0.0.0'
