name 'nodes-php'
version '0.2.2'
author 'nodesagency'
license 'MIT'
summary 'Puppet module to manage PHP on debian (and others)'
description 'Puppet module to manage PHP on debian (and others)'
project_page 'https://github.com/nodesagency/puppet-php'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt'
